### ISSUE TITLE
can't download data

### ISSUE THREAD

**Issue by Yeah2333** [oxford-robotics-institute/radar-robotcar-dataset-sdk#10]
Hi, i have finish [registration](http://ori.ox.ac.uk/datasets/radar-robotcar-dataset/registration) and i can find the dataset in my google drive. But i can't download using python script, so i check in manual test, i can download dataset in this link https://drive.google.com/file/d/1egbOZ4C4dFc37jx4HNnkEySTY8Y4gfMi.

`2022-05-23 17:16:33 ERROR : : error reading source directory: directory not found
2022-05-23 17:16:33 ERROR : Attempt 1/3 failed with 2 errors and: directory not found
2022-05-23 17:16:33 ERROR : : error reading source directory: directory not found
2022-05-23 17:16:33 ERROR : Attempt 2/3 failed with 2 errors and: directory not found
2022-05-23 17:16:34 ERROR : : error reading source directory: directory not found
2022-05-23 17:16:34 ERROR : Attempt 3/3 failed with 2 errors and: directory not found
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 2 (retrying may help)
Checks:                 0 / 0, -
Transferred:            0 / 0, -
Elapsed time:          0s
2022/05/23 17:16:34 Failed to copy with 2 errors: last error was: directory not found
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wangzhiyong/pointcloud_hw/env/lib/python3.6/site-packages/radar_robotcar_dataset_sdk/downloader/download.py", line 193, in <module>
    app.run(main)
  File "/home/wangzhiyong/pointcloud_hw/env/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/wangzhiyong/pointcloud_hw/env/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/wangzhiyong/pointcloud_hw/env/lib/python3.6/site-packages/radar_robotcar_dataset_sdk/downloader/download.py", line 180, in main
    downloaded_zip_file_path = gdrive_handler.download_filename(filename)
  File "/home/wangzhiyong/pointcloud_hw/env/lib/python3.6/site-packages/radar_robotcar_dataset_sdk/downloader/gdrive_handler.py", line 46, in download_filename
    subprocess.check_call(args)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/media/wangzhiyong/F2D6AC91D6AC579D/oxford/rclone', '--config', '/media/wangzhiyong/F2D6AC91D6AC579D/oxford/rclone_rrcd.conf', '--drive-shared-with-me', '--progress', 'copy', 'rrcd_drive:2019-01-10-11-46-21-radar-oxford-10k_Navtech_CTS350-X_Radar', '/media/wangzhiyong/F2D6AC91D6AC579D/oxford/']' returned non-zero exit status 3`

**Comment by mttgdd** [comment]
Thanks for the detail, can you provide me with the command line that you are using?

**Comment by Yeah2333** [comment]
Thanks for your prompt reply. The command i use is 
`python -m radar_robotcar_dataset_sdk.downloader.download \
        --sensors="Navtech CTS350-X Radar,NovAtel GPS / INS" \
        --download_folder /media/wangzhiyong/F2D6AC91D6AC579D/oxford/`

**Comment by Yeah2333** [comment]
I have finsih download dataset using google drive for desktop, and i still can't download dataset using python script.
